"""Add Deal model table

Revision ID: 0809e64d39d9
Revises: 3901518e151f
Create Date: 2025-10-24 14:42:34.030930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0809e64d39d9'
down_revision = '3901518e151f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('deal_date', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('car_request_id', sa.Integer(), nullable=False),
    sa.Column('accepted_bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_bid_id'], ['dealer_bid.id'], ),
    sa.ForeignKeyConstraint(['car_request_id'], ['car_requests.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accepted_bid_id')
    )
    op.drop_table('deal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('final_price', sa.FLOAT(), nullable=False),
    sa.Column('deal_date', sa.DATETIME(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), nullable=False),
    sa.Column('car_request_id', sa.INTEGER(), nullable=False),
    sa.Column('accepted_bid_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_bid_id'], ['dealer_bid.id'], ),
    sa.ForeignKeyConstraint(['car_request_id'], ['car_requests.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deals')
    # ### end Alembic commands ###
