"""Make CarRequest make and model nullable

Revision ID: 0b329635c6aa
Revises: 2a39348fbcf9
Create Date: 2025-10-12 12:10:29.769049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b329635c6aa'
down_revision = '2a39348fbcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_requests', schema=None) as batch_op:
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_requests', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
