"""Add detailed fields to dealer bids

Revision ID: 0d624a270d06
Revises: 3e20c750cf0b
Create Date: 2025-10-14 19:29:39.175773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d624a270d06'
down_revision = '3e20c750cf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('car_year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('extras', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['car_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealer_bid_timestamp'), ['timestamp'], unique=False)

    op.create_table('dealer_bid_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('dealer_bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_bid_id'], ['dealer_bid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dealer_bids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_bids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('dealer_id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['car_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dealer_bid_image')
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealer_bid_timestamp'))

    op.drop_table('dealer_bid')
    # ### end Alembic commands ###
