"""Add is_approved column to car table

Revision ID: 2077a5560e55
Revises: 4c842c14cc12
Create Date: 2025-10-02 16:21:57.611425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2077a5560e55'
down_revision = '4c842c14cc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
