"""Add order column to car_images with server_default

Revision ID: 223c09007dca
Revises: 28df7547de3e
Create Date: 2025-12-10 22:50:28.577455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223c09007dca'
down_revision = '28df7547de3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
