"""Add condition column to car table

Revision ID: 2a39348fbcf9
Revises: 0a6ea757b640
Create Date: 2025-10-11 22:42:53.788119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a39348fbcf9'
down_revision = '0a6ea757b640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('min_year', sa.Integer(), nullable=True),
    sa.Column('max_mileage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealer_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['car_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('condition')

    op.drop_table('dealer_bids')
    op.drop_table('car_requests')
    # ### end Alembic commands ###
