"""Add make and model to DealerBid model

Revision ID: 3901518e151f
Revises: 784299e1c8f8
Create Date: 2025-10-24 12:23:49.275053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3901518e151f'
down_revision = '784299e1c8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('model', sa.String(length=64), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('make')

    # ### end Alembic commands ###
