"""Integrate DealerBidImage model

Revision ID: 3b999e5a443f
Revises: 6124919d236c
Create Date: 2025-11-17 12:52:20.765265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b999e5a443f'
down_revision = '6124919d236c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_bid_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('dealer_bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_bid_id'], ['dealer_bid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=True))

    op.drop_table('dealer_bid_image')
    # ### end Alembic commands ###
