"""Add dealer and rental company roles to User

Revision ID: 3e20c750cf0b
Revises: 59c6d93b7d05
Create Date: 2025-10-12 16:10:04.453808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e20c750cf0b'
down_revision = '59c6d93b7d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dealer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_rental_company', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_rental_company')
        batch_op.drop_column('is_dealer')

    # ### end Alembic commands ###
