"""Add fcm_token to User

Revision ID: 40f26aadc3ab
Revises: 47563aa66bfc
Create Date: 2026-01-16 21:55:57.191441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f26aadc3ab'
down_revision = '47563aa66bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealer_review_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_dealer_review_dealer_id'))

    op.drop_table('dealer_review')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    op.create_table('dealer_review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dealer_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealer_review_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dealer_review_buyer_id'), ['buyer_id'], unique=False)

    # ### end Alembic commands ###
