"""Add conversation and chat message models

Revision ID: 5d08f6acdaaa
Revises: 0809e64d39d9
Create Date: 2025-11-02 19:16:44.915641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d08f6acdaaa'
down_revision = '0809e64d39d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('deal_date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('car_request_id', sa.Integer(), nullable=False),
    sa.Column('accepted_bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_bid_id'], ['dealer_bid.id'], ),
    sa.ForeignKeyConstraint(['car_request_id'], ['car_requests.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('final_price', sa.FLOAT(), nullable=False),
    sa.Column('deal_date', sa.DATETIME(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('dealer_id', sa.INTEGER(), nullable=False),
    sa.Column('car_request_id', sa.INTEGER(), nullable=False),
    sa.Column('accepted_bid_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_bid_id'], ['dealer_bid.id'], ),
    sa.ForeignKeyConstraint(['car_request_id'], ['car_requests.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accepted_bid_id')
    )
    op.drop_table('deal')
    op.drop_table('chat_messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
