"""Add trade-in request models

Revision ID: 6124919d236c
Revises: a3e31068cf67
Create Date: 2025-11-17 12:40:01.498671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6124919d236c'
down_revision = 'a3e31068cf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_in_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_in_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('trade_in_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trade_in_request_id'], ['trade_in_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dealer_bid_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_bid_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dealer_bid_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_bid_id'], ['dealer_bid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('trade_in_photos')
    op.drop_table('trade_in_requests')
    # ### end Alembic commands ###
