"""Add search_query table

Revision ID: 621092a4e10c
Revises: 3e27f6779c27
Create Date: 2026-02-07 19:36:21.121179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621092a4e10c'
down_revision = '3e27f6779c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_queries_query_text'), ['query_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_queries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_search_queries_query_text'))

    op.drop_table('search_queries')
    # ### end Alembic commands ###
