"""Implement deal acceptance models

Revision ID: 68fa79f92117
Revises: 0d624a270d06
Create Date: 2025-10-14 22:20:45.846223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fa79f92117'
down_revision = '0d624a270d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('deal_date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('car_request_id', sa.Integer(), nullable=False),
    sa.Column('accepted_bid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_bid_id'], ['dealer_bid.id'], ),
    sa.ForeignKeyConstraint(['car_request_id'], ['car_requests.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('car_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('accepted_bid_id', sa.Integer(), nullable=True))
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('fk_car_requests_customer_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_car_requests_accepted_bid_id_dealer_bid'), 'dealer_bid', ['accepted_bid_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_car_requests_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('customer_id')
        batch_op.drop_column('max_mileage')

    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('car_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_mileage', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_car_requests_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_car_requests_accepted_bid_id_dealer_bid', type_='foreignkey')
        batch_op.create_foreign_key('fk_car_requests_customer_id_user', 'user', ['customer_id'], ['id'])
        batch_op.alter_column('model',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('make',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('accepted_bid_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))

    op.drop_table('notification')
    op.drop_table('deal')
    # ### end Alembic commands ###
