"""Add payment_method to Deal model

Revision ID: 6e29b835faba
Revises: 7d0039246928
Create Date: 2025-11-05 12:32:19.992585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e29b835faba'
down_revision = '7d0039246928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))

    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_with_loan', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.drop_column('price_with_loan')

    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
