"""Add message_count to Conversation model

Revision ID: 6f42ee67d0c3
Revises: a22ee52ddd80
Create Date: 2025-11-03 13:54:56.516842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f42ee67d0c3'
down_revision = 'a22ee52ddd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('message_count')

    # ### end Alembic commands ###
