"""Add LeadScore model

Revision ID: 770e48809ec7
Revises: 6f42ee67d0c3
Create Date: 2025-11-03 18:52:17.877073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770e48809ec7'
down_revision = '6f42ee67d0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_scores')
    # ### end Alembic commands ###
