"""Add is_active status to Car model

Revision ID: 784299e1c8f8
Revises: b93ce3834014
Create Date: 2025-10-23 15:04:31.006607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784299e1c8f8'
down_revision = 'b93ce3834014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
