"""Add dealer_request_view and dealer_review tables

Revision ID: 7d0039246928
Revises: 3d1564644f48
Create Date: 2025-11-05 12:25:50.794307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0039246928'
down_revision = '3d1564644f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_request_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['car_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dealer_id', 'request_id', name='_dealer_request_uc')
    )
    with op.batch_alter_table('dealer_request_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealer_request_view_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dealer_request_view_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_request_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealer_request_view_request_id'))
        batch_op.drop_index(batch_op.f('ix_dealer_request_view_dealer_id'))

    op.drop_table('dealer_request_view')
    # ### end Alembic commands ###
