"""Add DealerReview model

Revision ID: 8f3fae648ade
Revises: 909de139f3fd
Create Date: 2025-11-05 11:29:07.662796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3fae648ade'
down_revision = '909de139f3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dealer_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealer_review_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dealer_review_dealer_id'), ['dealer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealer_review_dealer_id'))
        batch_op.drop_index(batch_op.f('ix_dealer_review_buyer_id'))

    op.drop_table('dealer_review')
    # ### end Alembic commands ###
