"""Add bank loan availability to Car model

Revision ID: 909de139f3fd
Revises: f7f593807054
Create Date: 2025-11-04 14:15:25.478891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909de139f3fd'
down_revision = 'f7f593807054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bank_loan_available', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('is_bank_loan_available')

    # ### end Alembic commands ###
