"""Add original_body to chat message

Revision ID: a22ee52ddd80
Revises: 5d08f6acdaaa
Create Date: 2025-11-03 12:02:37.765201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22ee52ddd80'
down_revision = '5d08f6acdaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('original_body')

    # ### end Alembic commands ###
