"""empty message

Revision ID: a38e3a4ebdcf
Revises: c9c8b501960a
Create Date: 2025-12-20 01:15:42.320154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38e3a4ebdcf'
down_revision = 'c9c8b501960a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_changes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('last_changes')

    # ### end Alembic commands ###
