"""Add image_url to DealerBid model

Revision ID: a3e31068cf67
Revises: 6e29b835faba
Create Date: 2025-11-07 15:28:44.337510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e31068cf67'
down_revision = '6e29b835faba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True, server_default=sa.text("''"))) # Added server_default
        batch_op.add_column(sa.Column('edit_point_deducted', sa.Boolean(), nullable=False, server_default=sa.text('0'))) # Added server_default for existing rows

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_bid', schema=None) as batch_op:
        batch_op.drop_column('edit_point_deducted')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
