"""Add listing_type and fixed_price to Car model

Revision ID: c372e6c1d53f
Revises: 215a023514c2
Create Date: 2025-10-18 12:44:55.715438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c372e6c1d53f'
down_revision = '215a023514c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('fixed_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('fixed_price')
        batch_op.drop_column('listing_type')

    # ### end Alembic commands ###
