"""Add target_car column to trade_in_requests

Revision ID: c9c8b501960a
Revises: bf3acd753cb2
Create Date: 2025-12-18 23:45:01.561224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c8b501960a'
down_revision = 'bf3acd753cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_in_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_car', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_in_requests', schema=None) as batch_op:
        batch_op.drop_column('target_car')

    # ### end Alembic commands ###
