"""Add document URLs to Car model

Revision ID: df1790abf7a5
Revises: 2077a5560e55
Create Date: 2025-10-03 23:54:11.137512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1790abf7a5'
down_revision = '2077a5560e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_history_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('inspection_report_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('inspection_report_url')
        batch_op.drop_column('service_history_url')

    # ### end Alembic commands ###
