"""Add transmission, drivetrain, and mileage to Car

Revision ID: e778d161d732
Revises: f24df5108848
Create Date: 2025-10-07 21:21:30.510277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e778d161d732'
down_revision = 'f24df5108848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transmission', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('drivetrain', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('mileage')
        batch_op.drop_column('drivetrain')
        batch_op.drop_column('transmission')

    # ### end Alembic commands ###
