"""Add fuel_type to Car model

Revision ID: f73d3aa7b05b
Revises: e778d161d732
Create Date: 2025-10-07 22:11:31.215444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73d3aa7b05b'
down_revision = 'e778d161d732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('fuel_type')

    # ### end Alembic commands ###
